spring.application.name=asgi-watch
server.port=8080

# PostgreSQL Configuration for local agsi database
spring.datasource.url=jdbc:postgresql://localhost:5432/agsi
spring.datasource.username=simon
spring.datasource.password=N0m1596.
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Static resources
spring.web.resources.static-locations=classpath:/static/
